### ISSUE TITLE
Request: nodejs code sample using impersonated credentials

### ISSUE THREAD

**Issue by answerquest** [salrashid123/gcpsamples#16]
Hi, thank you so much for bringing this all together.

https://github.com/salrashid123/gcpsamples/tree/master/impersonated_credentials  
Presently only java and python code samples available. Pls include nodejs samples too. In particular, I'm looking for nodejs pub/sub sample code that uses service account impersonation instead of fixed keys.

And in case this helps, here's a full list of scopes that we can put in `target_scopes` to enable the program to do more than just read: https://developers.google.com/identity/protocols/oauth2/scopes

**Comment by salrashid123** [comment]
impersonation for nodejs is almost done here;
   https://github.com/googleapis/google-auth-library-nodejs/pull/1207
