### ISSUE TITLE
Remove or pin use of a deprecated python package, google-cloud

### ISSUE THREAD

**Issue by crwilcox** [salrashid123/gcpsamples#2]
https://github.com/salrashid123/gcpsamples/blob/44981a64d9bda7cccbc185b5ad9d5b7244f3ec57/auth/service/pyapp/requirements.txt#L1 

This repository contains multiple setup.py or requirements.txt files that depends on 
the `google-cloud` package. This package is deprecated. If you wish to continue
to use this package, please pin the version to `google-cloud<0.34.0`. If you have
more time to dedicate to this, I would advise sorting out which sub-packages you
actually rely on and depending on them.

**Comment by salrashid123** [comment]
thanks!
https://github.com/salrashid123/gcpsamples/commit/1b83dbc77bf72643389e4650795f3cdf8ee5c893

**Comment by crwilcox** [comment]
Happy to help. Thanks for using our libs!
